### ISSUE TITLE
Please provide option to just get certificate and exit

### ISSUE THREAD

**Issue by Hubbitus** [kitspace/docker-nginx-certbot-plugin#2]
For now, after certificates issuing script [unconditionally enter to the endless loop](https://github.com/kitspace/docker-nginx-certbot-plugin/blob/1bea7dac4a8816c762454d98ea186bf8ca7252b7/command#L18).

Please provide some env var to just exit after certificate creation.

My use-case - I run your container on the server, and it is got SSL certificate, then it should stop and free all occupied ports. And Another server should start with 80 and 443 ports with obtained early certificates.

**Comment by kasbah** [comment]
Hey, this  project is not maintained any more as we just build nginx inside kitspace-v2 now. I woulnd't recommend using it without forking it and updating the underlying nginx. I'm going archive this repo, good luck!
